sudo: required
services: 
  - docker
language: python
branches:
  only:
    - travis_ci_linux
os:
  - linux


before_install:
  # create a docker container for 16.04 'pupil-ubuntu' and map working dir to travis
  # tail -f /dev/null enables us to view docker output in ci log
  - docker run -d --name pupil-ubuntu -v $(pwd):/travis pupillabs/pupil-docker-ubuntu:1.0 tail -f /dev/null
  - docker ps
  - ls -alR
script:
  - docker exec -t pupil-ubuntu bash -c "chmod +x travis &&
    cd deployment &&
    ./bundle.sh"