sudo: required
services: 
  - docker
language: python
branches:
  only:
    - travis_ci_linux
os:
  - linux

addons:
  apt:
    packages:
      - docker-ce

before_install:
  # create a docker container for 16.04 'pupil-ubuntu' and map working dir to travis
  # tail -f /dev/null enables us to view docker output in ci log
  - docker --version
  - docker run -d --name pupil-ubuntu --mount type=bind,source=$TRAVIS_BUILD_DIR,target=/root/pupil pupillabs/pupil-docker-ubuntu:1.0 tail -f /dev/null
  - docker ps
script:
  - docker exec -t pupil-ubuntu bash -c "chmod +x pupil &&
    cd pupil/deployment &&
    ./bundle.sh"