language: python
python: 
  - '3.6'
branches:
  only:
    - travis_ci_linux
os:
  - linux
sudo: true
before_install:
  # add sourcelines
  - sudo -E add-apt-repository -y ppa:jonathonf/ffmpeg-3
  - sudo -E add-apt-repository -y ppa:bzindovic/suitesparse-bugfix-1319687
  # update
  - sudo -E apt-get -yq update
  # add packages
  - sudo -E apt-get install -yq --no-install-suggests --no-install-recommends \
    pkg-config build-essential nasm python3-setuptools libusb-1.0-0-dev \
    python3-dev python3-pip python3-numpy python3-scipy libglew-dev libglfw3-dev libtbb-dev \
    libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev \
    ffmpeg libav-tools x264 x265 libportaudio2 portaudio19-dev \
    libboost-dev libboost-python-dev libgoogle-glog-dev libatlas-base-dev libeigen3-dev libsuitesparse-dev \
install:
  # opencv
  - git clone https://github.com/opencv/opencv
  - cd opencv && mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DWITH_TBB=ON -DWITH_CUDA=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=ON ..
  - make -j2
  - make install
  - ldconfig
  # turbojpeg
  - wget -O libjpeg-turbo.tar.gz https://sourceforge.net/projects/libjpeg-turbo/files/1.5.1/libjpeg-turbo-1.5.1.tar.gz/download
  - tar xvzf libjpeg-turbo.tar.gz
  - cd libjpeg-turbo-1.5.1
  - ./configure --enable-static=no --prefix=/usr/local
  - make install
  - ldconfig  
  # libusb - only required for 17.10 - but will test here as well
  - sudo cp '~/path to your fixed binary/libusb-1.0.so.0' '/lib/x86_64-linux-gnu/libusb-1.0.so.0'
  # libuvc
  - git clone https://github.com/pupil-labs/libuvc
  - cd libuvc
  - mkdir build
  - cd build
  - cmake ..
  - make && make install
  # pip install - todo make requirements.txt file
  - pip install numexpr
  - pip install cython
  - pip install psutil
  - pip install pyzmq
  - pip install msgpack_python
  - pip install pyopengl
  - pip install pyaudio
  - pip install git+https://github.com/zeromq/pyre
  - pip install git+https://github.com/pupil-labs/PyAV
  - pip install git+https://github.com/pupil-labs/pyuvc
  - pip install git+https://github.com/pupil-labs/pyndsi
  - pip install git+https://github.com/pupil-labs/pyglui
  # 3d model dependencies
  - git clone https://ceres-solver.googlesource.com/ceres-solver
  - cd ceres-solver
  - mkdir build && cd build
  - cmake .. -DBUILD_SHARED_LIBS=ON
  - make -j3
  - make test
  - make install
  - sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/ceres.conf'
  - ldconfig
script:
  - ./deployment/bundle.sh