sudo: required
services: 
  - docker
language: python
branches:
  only:
    - travis_ci_linux
os:
  - linux


before_install:
  # create a docker container for 16.04 'pupil-ubuntu' and map working dir to travis
  # tail -f /dev/null enables us to view docker output in ci log
  - docker run -d --name pupil-ubuntu -v $(pwd):/travis pupillabs/pupil-docker-ubuntu:latest tail -f /dev/null
  - docker ps
script:
  - ./deployment/bundle.sh